// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwGs8b-Xrj2tXhnPg2ax-Y9vrX9oF1xKU',
    appId: '1:643818207666:web:cae902231c3eb191be8cab',
    messagingSenderId: '643818207666',
    projectId: 'app-prototype-67e87',
    authDomain: 'app-prototype-67e87.firebaseapp.com',
    storageBucket: 'app-prototype-67e87.appspot.com',
    measurementId: 'G-XSZ2RVJVBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAqvYJbHgnB-_oihmKz6LrJUAmfecZz60',
    appId: '1:643818207666:android:56dac40a342f4d97be8cab',
    messagingSenderId: '643818207666',
    projectId: 'app-prototype-67e87',
    storageBucket: 'app-prototype-67e87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcqnEnzqRun0bxVWjJGADoa1FlCp8pjIg',
    appId: '1:643818207666:ios:6ff0683d6b661a88be8cab',
    messagingSenderId: '643818207666',
    projectId: 'app-prototype-67e87',
    storageBucket: 'app-prototype-67e87.appspot.com',
    iosBundleId: 'com.example.appPrototype',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcqnEnzqRun0bxVWjJGADoa1FlCp8pjIg',
    appId: '1:643818207666:ios:83092ceea691e419be8cab',
    messagingSenderId: '643818207666',
    projectId: 'app-prototype-67e87',
    storageBucket: 'app-prototype-67e87.appspot.com',
    iosBundleId: 'com.example.appPrototype.RunnerTests',
  );
}
